#___________________________________________________________________________________________________________________________________________
inherit RepresentationComet_CFC CommonFC

#___________________________________________________________________________________________________________________________________________
method RepresentationComet_CFC constructor {} {
 this inherited
 set this(RepresentedComet) ""
 set this(unique_id) 0
}

#___________________________________________________________________________________________________________________________________________
method RepresentationComet_CFC dispose {} {
 this inherited
}

#___________________________________________________________________________________________________________________________________________
method RepresentationComet_CFC get_a_unique_id {} {
 incr this(unique_id)
 return $this(unique_id)
}

#___________________________________________________________________________________________________________________________________________
method RepresentationComet_CFC Instanciate_a_complete_COMET {} {
 if {[string equal $this(RepresentedComet) ""]} {return ""}
 set L_classes [gmlObject info classes $this(RepresentedComet)]
 if {[lsearch $L_classes Logical_consistency] != -1} {
   set name "${objName}_Generated_COMET_$this(RepresentedComet)_[this get_a_unique_id]"
   $this(RepresentedComet) $name "$this(RepresentedComet)" "Generated by $objName"
   return $name
  } else {if {[lsearch $L_classes GDD_Node] != -1} {            
		   # Get the related implementations in PMs
		    dsl_q QUERY "?n : $this(RepresentedComet) : NODE()<-REL(type~=GDD_inheritance && type!=GDD_restriction)*<REL(type~=GDD_implementation)<-\$n()"
			set L_PMs {}
			foreach GDD_node [lindex [lindex [dsl_q get_Result] 0] 1] {
			  set class_PM [lindex [$GDD_node get_L_factories] 0]			  
			  set name_PM "${objName}_Generated_COMET_${class_PM}_[this get_a_unique_id]"
			    $class_PM $name_PM "$class_PM" "Generated by $objName"
				lappend L_PMs $name_PM
			 }
		   # Get the related LC
		    dsl_q QUERY "?n : $this(RepresentedComet) : NODE()->REL(type~=GDD_inheritance && type!=GDD_restriction)*>REL(type~=GDD_concretization)->\$n(type == GDD_C&T)"
		    set GDD_LC [lindex [lindex [dsl_q get_Result] 0] 1]
			set class_LC [lindex [$GDD_LC get_L_factories] 0]
			set name_LC "${objName}_Generated_COMET_${class_LC}_[this get_a_unique_id]"
			  $class_LC $name_LC "$class_LC" "LC Generated by $objName to correspond to $this(RepresentedComet)"
		   # Plug PMs to the LC
		    ${name_LC}_LM_LP configure -set_L_PM $L_PMs -set_L_actives_PM $L_PMs
			return $name_LC
           }		  
         }
 return ""
}

#___________________________________________________________________________________________________________________________________________
Generate_accessors RepresentationComet_CFC [list RepresentedComet]

#___________________________________________________________________________________________________________________________________________
#___________________________________________________________________________________________________________________________________________
#___________________________________________________________________________________________________________________________________________
proc P_L_methodes_get_RepresentationComet {} {return [list {get_RepresentedComet { }} {Instanciate_a_complete_COMET {}}]}
proc P_L_methodes_set_RepresentationComet {} {return [list {set_RepresentedComet {c}}]}
